const mongoose = require('mongoose');

const OrderSchema = new mongoose.Schema({
    orderId: { type: String, required: true }, // Custom ID generated by frontend or short ID
    user: {
        email: { type: String, required: true },
        address: { type: String, required: true }
    },
    items: [{
        productId: String,
        name: String,
        size: String,
        price: Number,
        quantity: Number,
        image: String,
        category: String,
        extras: [String],
        note: String
    }],
    total: { type: Number, required: true },
    status: { type: String, enum: ['Pending', 'Delivered'], default: 'Pending' },
    date: { type: String } // Storing date string as formatted in frontend for now, or use createdAt
}, { timestamps: true });

module.exports = mongoose.model('Order', OrderSchema);
