const mongoose = require('mongoose');

const OrderSchema = new mongoose.Schema({
    orderId: { type: String, required: true, unique: true }, // Custom ID generated by frontend or short ID
    user: {
        email: { type: String, required: true },
        address: { type: String, required: true },
        phone: { type: String }
    },
    items: [{
        productId: String,
        name: String,
        size: String,
        price: Number,
        quantity: Number,
        image: String,
        category: String,
        extras: [String],
        note: String
    }],
    total: { type: Number, required: true },
    deliveryFee: { type: Number, default: 0 },
    deliveryMethod: { type: String, enum: ['Delivery', 'Pick-up'], default: 'Delivery' },
    status: { type: String, enum: ['Pending', 'Preparing', 'Ready for Delivery', 'Out for Delivery', 'Delivered'], default: 'Pending' },
    estimatedTotalPrepTime: { type: Number, default: 0 },
    pings: [{
        at: { type: Date, default: Date.now },
        acknowledged: { type: Boolean, default: false },
        acknowledgedAt: { type: Date }
    }],
    assignedRider: { type: mongoose.Schema.Types.ObjectId, ref: 'Rider' },
    date: { type: String }, // Storing date string as formatted in frontend for now, or use createdAt
    deliveredAt: { type: Date },
    deliveredBy: { type: String }
}, { timestamps: true });

module.exports = mongoose.model('Order', OrderSchema);
